events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 5172;

        location / {
            root /usr/share/nginx/html;
            # Renvoie index.html pour toutes les routes (nécessaire pour le routing React)
            try_files $uri $uri/ /index.html;
        }
    }
}