@baseUrl = http://localhost:3000


### Register a new member
# Run this once to create the account in the DB
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "student@vinci.be",
  "password": "password123"
}
### Login to refresh the Token
# This script captures the token and saves it to the global environment
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "lea@mail.com",
  "password": "1"
}

> {%
  client.global.set("token", response.body.token);
%}


### Get my notifications unreadOnly = true
GET {{baseUrl}}/notifications/member/me?unreadOnly=true
Authorization:{{token}}

### GET my notifications unreadOnly = false
GET {{baseUrl}}/notifications/member/me?unreadOnly=false
Authorization:{{token}}

### GET unreadCount
GET {{baseUrl}}/notifications/member/me/unread-count
Authorization: {{token}}


### Mark a specific notification as read
PATCH {{baseUrl}}/notifications/1/read
Authorization: {{token}}

### Mark a specific notification as read , error case notif not found
PATCH {{baseUrl}}/notifications/999/read
Authorization: {{token}}
