@baseUrl = http://localhost:3000

# ----------- TEAM CREATION -----------

### 1: REGISTER A NEW MEMBER A
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "userA@test.com",
  "password": "Password123!",
  "tag": "UserA"
}

### 2: LOGIN USER A
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "userA@test.com",
  "password": "Password123!"
}

> {% client.global.set("tokenA", response.body.token); %}

### 3: CREATE A TEAM (201)
POST {{baseUrl}}/teams/
Content-Type: application/json
Authorization: {{tokenA}}

{
  "name": "TeamA"
}

### 4: DUPLICATE TEAM (409)
POST {{baseUrl}}/teams/
Content-Type: application/json
Authorization: {{tokenA}}

{
  "name": "TeamA"
}

### 5: NO AUTH (403)
POST {{baseUrl}}/teams/
Content-Type: application/json

{
  "name": "NoAuth"
}

### 6: BLANK NAME (400)
POST {{baseUrl}}/teams/
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "  "
}

### 7: GET TEAM DETAILS AS VISITOR
GET {{baseUrl}}/teams/4/details


# ----------- QUIT TEAM -----------

### 8. REGISTER USER B (no team)
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "userB@test.com",
  "password": "Password123!",
  "tag": "UserB"
}

### 9. LOGIN USER B
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "userB@test.com",
  "password": "Password123!"
}

> {% client.global.set("tokenB", response.body.token); %}

### 10. QUIT TEAM WITHOUT BEING IN ONE (400)
POST {{baseUrl}}/teams/quit
Authorization: {{tokenB}}


### ----------- RESIGN MANAGER -----------

### 11. RESIGN WITHOUT REPLACEMENT (ONLY manager) -> 409
PUT {{baseUrl}}/teams/4/resign
Authorization: {{tokenA}}


# ----------- ADVANCED RESIGN (WITH REPLACEMENT) -----------

### 12. REGISTER USER C
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "userC@test.com",
  "password": "Password123!",
  "tag": "UserC"
}

### 13. LOGIN USER C
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "userC@test.com",
  "password": "Password123!"
}

> {% client.global.set("tokenC", response.body.token); %}

### 14. RESIGN WITH REPLACEMENT NOT IN TEAM (400)
PUT {{baseUrl}}/teams/4/resign?replacementId=3
Authorization: {{tokenA}}